In [1]:
import pandas as pd
import plotly

# Importar dataset SNIS e abrir como um Pandas DataFrame

In [2]:
# Abrir, Ler e atribuir a uma variável os dados .csv do snis de 2021
df_snis = pd.read_csv('snis_municipios.csv', sep=';', decimal=',', thousands='.', encoding='utf-16-le', index_col=False)

# Exibir o dataframe
df_snis.head()

,Código do IBGE,Código do Município,Município,Estado,Ano de Referência,Prestadores,Serviços,Natureza Jurídica,G06A - População urbana residente do(s) município(s) com abastecimento de água,G06B - População urbana residente do(s) município(s) com esgotamento sanitário,...,IN043_RS - Custo unitário médio do serviço de varrição (prefeitura + empresas contratadas),IN044_RS - Produtividade média dos varredores (prefeitura + empresas contratadas),IN045_RS - Taxa de varredores em relação à população urbana,IN046_RS - Incidência do custo do serviço de varrição no custo total com manejo de rsu,IN047_RS - Incidência de varredores no total de empregados no manejo de rsu,IN048_RS - Extensão total anual varrida per capita,IN051_RS - Taxa de capinadores em relação à população urbana,IN052_RS - Incidência de capinadores no total empregados no manejo de rsu,IN053_RS - Taxa de material recolhido pela coleta seletiva (exceto mat. orgânica) em relação à quantidade total coletada de resíduos sól. domésticos,IN054_RS - Massa per capita de materiais recicláveis recolhidos via coleta seletiva
0,3300100,330010,Angra dos Reis,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,202458.0,202458.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.65
1,3300100,330010,Angra dos Reis,RJ,2020,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,199446.0,199446.0,...,NaN,NaN,0.88,NaN,40.42,NaN,0.25,11.55,NaN,0.85
2,3300100,330010,Angra dos Reis,RJ,2019,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,196306.0,196306.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96
3,NaN,330010,Angra dos Reis,RJ,2018,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,NaN,193052.0,193052.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.47
4,NaN,330010,Angra dos Reis,RJ,2017,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,NaN,187477.0,187477.0,...,NaN,NaN,0.93,30.98,40.42,NaN,0.27,11.55,11.91,31.31

# Data Cleaning

## Processo de Renomear as colunas do DataFrame

### Inicialmente separamos as colunas de código do SNIS das Colunas que não são de código para tratá-las de forma diferente.

**Atenção:** há 2 formas de iterar nas colunas do dataframe e retornar listas com os nomes das colunas, as duas formas estão descritas abaixo, são elas: List Comprehension e Laço For

In [3]:
# FORMAS DE FAZER LISTAS UTILIZANDO 'list comprehension'

# Construir uma lista "colunas_sem_codigo" iterando nas colunas até 8 do "df"
colunas_sem_codigo = [coluna for coluna in df_snis.columns[:8]]
# Construir uma lista "colunas_com_codigo" iterando nas colunas do "df" que não estão na lista "colunas_sem_codigo"
colunas_com_codigo = [coluna for coluna in df_snis.columns if coluna not in colunas_sem_codigo]

# OUTRA FORMA DE FAZER LISTAS UTILIZANDO Laço For

'''# Cria uma lista com o nome das colunas
# Itera nas colunas até 8 e adiciona/append a coluna na lista
colunas_sem_codigo = []
for coluna in df.columns[:8]:
    colunas_sem_codigo.append(coluna)

# Cria uma lista com o nome das colunas
# Itera nas colunas que não fazem parte da lista "colunas_sem_codigo"
# adiciona/append a coluna na lista "coluna_com_codigo"
colunas_com_codigo = []
for col in df.columns:
    if col not in colunas_sem_codigo:
        colunas_com_codigo.append(col)'''

'# Cria uma lista com o nome das colunas\n# Itera nas colunas até 8 e adiciona/append a coluna na lista\ncolunas_sem_codigo = []\nfor coluna in df.columns[:8]:\n    colunas_sem_codigo.append(coluna)\n\n# Cria uma lista com o nome das colunas\n# Itera nas colunas que não fazem parte da lista "colunas_sem_codigo"\n# adiciona/append a coluna na lista "coluna_com_codigo"\ncolunas_com_codigo = []\nfor col in df.columns:\n    if col not in colunas_sem_codigo:\n        colunas_com_codigo.append(col)'

In [4]:
# Limpar o nome textual e deixar somente os códigos das informações e indicadores do SNIS no dataframe "colunas"
colunas_com_codigo = [x[:x.find('-') -1 ] for x in colunas_com_codigo]

# Reunir as duas listas de colunas, com e sem código, em uma lista "colunas"
colunas = colunas_sem_codigo + colunas_com_codigo

# Exibir as colunas
colunas

['Código do IBGE',
 'Código do Município',
 'Município',
 'Estado',
 'Ano de Referência',
 'Prestadores',
 'Serviços',
 'Natureza Jurídica',
 'G06A',
 'G06B',
 'G12A',
 'G12B',
 'GE008',
 'GE009',
 'GE010',
 'GE011',
 'POP_TOT',
 'POP_URB',
 'GE201',
 'GE202',
 'AG001',
 'AG002',
 'AG003',
 'AG004',
 'AG005',
 'AG006',
 'AG007',
 'AG008',
 'AG010',
 'AG011',
 'AG012',
 'AG013',
 'AG014',
 'AG015',
 'AG017',
 'AG018',
 'AG019',
 'AG020',
 'AG021',
 'AG022',
 'AG024',
 'AG026',
 'AG027',
 'AG028',
 'ES001',
 'ES002',
 'ES003',
 'ES004',
 'ES005',
 'ES006',
 'ES007',
 'ES008',
 'ES009',
 'ES012',
 'ES013',
 'ES014',
 'ES015',
 'ES026',
 'ES028',
 'FN001',
 'FN002',
 'FN003',
 'FN004',
 'FN005',
 'FN006',
 'FN007',
 'FN008',
 'FN010',
 'FN011',
 'FN013',
 'FN014',
 'FN015',
 'FN016',
 'FN017',
 'FN018',
 'FN019',
 'FN020',
 'FN021',
 'FN022',
 'FN023',
 'FN024',
 'FN025',
 'FN026',
 'FN027',
 'FN028',
 'FN030',
 'FN031',
 'FN032',
 'FN033',
 'FN034',
 'FN035',
 'FN036',
 'FN037',
 'FN038',
 'FN039',
 'FN041',
 'FN042',
 'FN043',
 'FN044',
 'FN045',
 'FN046',
 'FN047',
 'FN048',
 'FN051',
 'FN052',
 'FN053',
 'FN054',
 'FN055',
 'FN056',
 'FN057',
 'FN058',
 'QD001',
 'QD002',
 'QD003',
 'QD004',
 'QD006',
 'QD007',
 'QD008',
 'QD009',
 'QD011',
 'QD012',
 'QD015',
 'QD016',
 'QD017',
 'QD019',
 'QD020',
 'QD021',
 'QD022',
 'QD023',
 'QD024',
 'QD025',
 'QD026',
 'QD027',
 'QD028',
 'QD029',
 'CA001',
 'CA002',
 'CA003',
 'CA004',
 'CA005',
 'CA006',
 'CA007',
 'CA008',
 'CA009',
 'CC010',
 'CC011',
 'CC012',
 'CC013',
 'CC014',
 'CC015',
 'CC016',
 'CC017',
 'CC018',
 'CC019',
 'CC020',
 'CO001',
 'CO002',
 'CO003',
 'CO004',
 'CO008',
 'CO012',
 'CO013',
 'CO014',
 'CO019',
 'CO020',
 'CO021',
 'CO022',
 'CO050',
 'CO051',
 'CO052',
 'CO053',
 'CO054',
 'CO055',
 'CO056',
 'CO057',
 'CO058',
 'CO059',
 'CO060',
 'CO061',
 'CO062',
 'CO063',
 'CO064',
 'CO065',
 'CO066',
 'CO067',
 'CO068',
 'CO069',
 'CO070',
 'CO071',
 'CO072',
 'CO073',
 'CO074',
 'CO075',
 'CO076',
 'CO077',
 'CO078',
 'CO079',
 'CO080',
 'CO081',
 'CO082',
 'CO083',
 'CO084',
 'CO085',
 'CO086',
 'CO087',
 'CO088',
 'CO089',
 'CO090',
 'CO091',
 'CO092',
 'CO093',
 'CO094',
 'CO095',
 'CO096',
 'CO097',
 'CO098',
 'CO099',
 'CO100',
 'CO101',
 'CO102',
 'CO103',
 'CO104',
 'CO105',
 'CO106',
 'CO107',
 'CO108',
 'CO109',
 'CO110',
 'CO111',
 'CO112',
 'CO113',
 'CO114',
 'CO115',
 'CO116',
 'CO117',
 'CO118',
 'CO119',
 'CO120',
 'CO121',
 'CO122',
 'CO123',
 'CO124',
 'CO125',
 'CO126',
 'CO127',
 'CO128',
 'CO129',
 'CO130',
 'CO131',
 'CO133',
 'CO134',
 'CO135',
 'CO136',
 'CO137',
 'CO138',
 'CO139',
 'CO140',
 'CO141',
 'CO142',
 'CO143',
 'CO144',
 'CO145',
 'CO146',
 'CO147',
 'CO148',
 'CO149',
 'CO150',
 'CO151',
 'CO152',
 'CO154',
 'CO155',
 'CO156',
 'CO157',
 'CO158',
 'CO159',
 'CO160',
 'CO161',
 'CO162',
 'CO163',
 'CO164',
 'CO165',
 'CO170',
 'CO171',
 'CO172',
 'CO173',
 'CO174',
 'CO175',
 'CP001',
 'CP002',
 'CP003',
 'CP004',
 'CS001',
 'CS002',
 'CS009',
 'CS010',
 'CS011',
 'CS012',
 'CS013',
 'CS014',
 'CS022',
 'CS023',
 'CS024',
 'CS025',
 'CS026',
 'CS027',
 'CS028',
 'CS029',
 'CS030',
 'CS031',
 'CS032',
 'CS033',
 'CS034',
 'CS035',
 'CS036',
 'CS037',
 'CS038',
 'CS039',
 'CS040',
 'CS041',
 'CS042',
 'CS043',
 'CS044',
 'CS045',
 'CS046',
 'CS047',
 'CS048',
 'CS049',
 'CS050',
 'CS053',
 'CS054',
 'CS055',
 'CS056',
 'CS057',
 'CS058',
 'CS059',
 'CS060',
 'FN201',
 'FN202',
 'FN203',
 'FN204',
 'FN205',
 'FN206',
 'FN207',
 'FN208',
 'FN209',
 'FN210',
 'FN211',
 'FN212',
 'FN213',
 'FN214',
 'FN215',
 'FN216',
 'FN217',
 'FN218',
 'FN219',
 'FN220',
 'FN221',
 'FN222',
 'FN223',
 'FN224',
 'FN225',
 'FN226',
 'FN227',
 'OS001',
 'OS003',
 'OS004',
 'OS005',
 'OS006',
 'OS007',
 'OS008',
 'OS009',
 'OS010',
 'OS011',
 'OS012',
 'OS014',
 'OS015',
 'OS016',
 'OS017',
 'OS018',
 'OS019',
 'OS020',
 'OS021',
 'OS022',
 'OS023',
 'OS025',
 'OS026',
 'OS027',
 'OS028',
 'OS029',
 'OS030',
 'OS031',
 'OS032',
 'OS033',
 'OS040',
 'OS041',
 'OS042',
 'OS043',
 'OS044',
 'OS045',
 'OS046',
 'OS047',
 'OS048',
 'OS049',
 'OS050',
 'OS051',
 'OS052',
 'OS053',
 'PO001',
 'PO002',
 'PO004',
 'PO005',
 'PO006',
 'PO007',
 'PO008',
 'PO009',
 'PO010',
 'PO011',
 'PO012',
 'PO013',
 'PO014',
 'PO015',
 'PO016',
 'PO017',
 'PO018',
 'PO019',
 'PO020',
 'PO021',
 'PO022',
 'PO023',
 'PO024',
 'PO025',
 'PO026',
 'PO027',
 'PO028',
 'PO029',
 'PO031',
 'PO033',
 'PO034',
 'PO035',
 'PO036',
 'PO037',
 'PO038',
 'PO039',
 'PO040',
 'PO041',
 'PO042',
 'PO043',
 'PO044',
 'PO045',
 'PO046',
 'PO047',
 'PO048',
 'PO049',
 'PO050',
 'PO051',
 'RS003',
 'RS004',
 'RS008',
 'RS009',
 'RS020',
 'RS021',
 'RS022',
 'RS023',
 'RS024',
 'RS025',
 'RS026',
 'RS027',
 'RS028',
 'RS030',
 'RS031',
 'RS034',
 'RS036',
 'RS038',
 'RS039',
 'RS040',
 'RS041',
 'RS042',
 'RS043',
 'RS044',
 'RS045',
 'RS046',
 'TB001',
 'TB002',
 'TB003',
 'TB004',
 'TB005',
 'TB006',
 'TB007',
 'TB008',
 'TB009',
 'TB010',
 'TB011',
 'TB012',
 'TB013',
 'TB014',
 'TB015',
 'TB016',
 'TB017',
 'TB018',
 'TB019',
 'TB020',
 'TB021',
 'TB022',
 'TB023',
 'TB024',
 'TB025',
 'TB026',
 'TB027',
 'TB028',
 'TB029',
 'TB030',
 'TB031',
 'TB032',
 'TB033',
 'TB034',
 'TB035',
 'VA001',
 'VA002',
 'VA003',
 'VA004',
 'VA010',
 'VA011',
 'VA012',
 'VA016',
 'VA020',
 'VA021',
 'VA030',
 'VA031',
 'VA032',
 'VA033',
 'VA034',
 'VA035',
 'VA036',
 'VA038',
 'VA039',
 'IN001_AE',
 'IN002_AE',
 'IN003_AE',
 'IN004_AE',
 'IN005_AE',
 'IN006_AE',
 'IN007_AE',
 'IN008_AE',
 'IN009_AE',
 'IN010_AE',
 'IN011_AE',
 'IN012_AE',
 'IN013_AE',
 'IN014_AE',
 'IN015_AE',
 'IN016_AE',
 'IN017_AE',
 'IN018_AE',
 'IN019_AE',
 'IN020_AE',
 'IN021_AE',
 'IN022_AE',
 'IN023_AE',
 'IN024_AE',
 'IN025_AE',
 'IN026_AE',
 'IN027_AE',
 'IN028_AE',
 'IN029_AE',
 'IN030_AE',
 'IN031_AE',
 'IN032_AE',
 'IN033_AE',
 'IN034_AE',
 'IN035_AE',
 'IN036_AE',
 'IN037_AE',
 'IN038_AE',
 'IN039_AE',
 'IN040_AE',
 'IN041_AE',
 'IN042_AE',
 'IN043_AE',
 'IN044_AE',
 'IN045_AE',
 'IN046_AE',
 'IN047_AE',
 'IN048_AE',
 'IN049_AE',
 'IN050_AE',
 'IN051_AE',
 'IN052_AE',
 'IN053_AE',
 'IN054_AE',
 'IN055_AE',
 'IN056_AE',
 'IN057_AE',
 'IN058_AE',
 'IN059_AE',
 'IN060_AE',
 'IN071_AE',
 'IN072_AE',
 'IN073_AE',
 'IN074_AE',
 'IN075_AE',
 'IN076_AE',
 'IN077_AE',
 'IN079_AE',
 'IN080_AE',
 'IN082_AE',
 'IN083_AE',
 'IN084_AE',
 'IN085_AE',
 'IN101_AE',
 'IN102_AE',
 'IN001_RS',
 'IN002_RS',
 'IN003_RS',
 'IN004_RS',
 'IN005_RS',
 'IN006_RS',
 'IN007_RS',
 'IN008_RS',
 'IN010_RS',
 'IN011_RS',
 'IN014_RS',
 'IN015_RS',
 'IN016_RS',
 'IN017_RS',
 'IN018_RS',
 'IN019_RS',
 'IN021_RS',
 'IN022_RS',
 'IN023_RS',
 'IN024_RS',
 'IN025_RS',
 'IN026_RS',
 'IN027_RS',
 'IN028_RS',
 'IN029_RS',
 'IN030_RS',
 'IN031_RS',
 'IN032_RS',
 'IN033_RS',
 'IN034_RS',
 'IN035_RS',
 'IN036_RS',
 'IN037_RS',
 'IN038_RS',
 'IN039_RS',
 'IN040_RS',
 'IN041_RS',
 'IN042_RS',
 'IN043_RS',
 'IN044_RS',
 'IN045_RS',
 'IN046_RS',
 'IN047_RS',
 'IN048_RS',
 'IN051_RS',
 'IN052_RS',
 'IN053_RS',
 'IN054_RS']

In [5]:
# Atribuir o nome limpo das colunas que estão no dataframe "colunas" ao dataframe "df"
df_snis.columns = colunas

# Renomear os headers de todas as colunas para minúsculo
df_snis.columns = df_snis.columns.str.lower()

# Renomear os headers das colunas iniciais
df_snis = df_snis.rename(columns={"código do ibge": "cd_mun7", "código do município": "cd_mun6", "município":"nm_mun", "estado":"uf", "ano de referência":"ano_ref", 'serviços':'servicos', 'natureza jurídica':'nat_jur'})

# Exibir os registros iniciais
df_snis.head()

,cd_mun7,cd_mun6,nm_mun,uf,ano_ref,prestadores,servicos,nat_jur,g06a,g06b,...,in043_rs,in044_rs,in045_rs,in046_rs,in047_rs,in048_rs,in051_rs,in052_rs,in053_rs,in054_rs
0,3300100,330010,Angra dos Reis,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,202458.0,202458.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.65
1,3300100,330010,Angra dos Reis,RJ,2020,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,199446.0,199446.0,...,NaN,NaN,0.88,NaN,40.42,NaN,0.25,11.55,NaN,0.85
2,3300100,330010,Angra dos Reis,RJ,2019,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,196306.0,196306.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.96
3,NaN,330010,Angra dos Reis,RJ,2018,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,NaN,193052.0,193052.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,82.47
4,NaN,330010,Angra dos Reis,RJ,2017,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,NaN,187477.0,187477.0,...,NaN,NaN,0.93,30.98,40.42,NaN,0.27,11.55,11.91,31.31

## Substituir NaN por vazio

In [6]:
# Substitui os valores NaN por vazio
df_snis = df_snis.fillna("")

# Exibir o dataframe
df_snis

,cd_mun7,cd_mun6,nm_mun,uf,ano_ref,prestadores,servicos,nat_jur,g06a,g06b,...,in043_rs,in044_rs,in045_rs,in046_rs,in047_rs,in048_rs,in051_rs,in052_rs,in053_rs,in054_rs
0,3300100,330010,Angra dos Reis,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,202458.0,202458.0,...,,,,,,,,,,27.65
1,3300100,330010,Angra dos Reis,RJ,2020,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,199446.0,199446.0,...,,,0.88,,40.42,,0.25,11.55,,0.85
2,3300100,330010,Angra dos Reis,RJ,2019,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,196306.0,196306.0,...,,,,,,,,,,0.96
3,,330010,Angra dos Reis,RJ,2018,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,,193052.0,193052.0,...,,,,,,,,,,82.47
4,,330010,Angra dos Reis,RJ,2017,[33001011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Água | Res. Sólidos,,187477.0,187477.0,...,,,0.93,30.98,40.42,,0.27,11.55,11.91,31.31
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
456,3306305,330630,Volta Redonda,RJ,2020,[33063011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,Autarquia | Administração pública direta,273864.0,273864.0,...,104.29,1.43,0.54,21.8,25.82,0.24,0.85,40.38,,5.89
457,3306305,330630,Volta Redonda,RJ,2019,[33063011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,Autarquia | Administração pública direta,272888.0,272888.0,...,90.63,1.8,0.47,16.82,29.95,0.26,0.42,26.89,,8.43
458,,330630,Volta Redonda,RJ,2018,[33063011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,,271875.0,271875.0,...,90.63,1.94,0.46,17.41,14.7,0.28,1.97,62.43,,2.95
459,,330630,Volta Redonda,RJ,2017,[33063011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,,265081.0,265081.0,...,90.63,1.71,0.47,13.92,21.16,0.25,1.2,54.1,,2.45
460,TOTAL da AMOSTRA:,---,---,---,---,---,---,---,82771898.0,79154325.0,...,,,,,,,,,,

## Abaixo vamos estudar a estrutura e o modelo de dados do nosso DataFrame para conhecê-lo um pouco melhor

In [7]:
# Exibindo as informações do dataframe
df_snis.info()

# Aqui temos informações sobre a quantidade de linhas e colunas e os tipos de dados que existem em nosso dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 461 entries, 0 to 460
Columns: 658 entries, cd_mun7 to in054_rs
dtypes: int64(2), object(656)
memory usage: 2.3+ MB

In [8]:
# Exibir os tipos de dados como uma lista em que apareça o header da coluna e o tipo de dado

# Obtenha os headers de coluna e dtypes
headers = df_snis.columns
dtypes = df_snis.dtypes

# Crie um laço for para iterar sobre os headers de coluna
for header in headers:
    # Imprima o header de coluna e o dtype
    print(f"{header} - {dtypes[header]}")

cd_mun7 - object
cd_mun6 - object
nm_mun - object
uf - object
ano_ref - object
prestadores - object
servicos - object
nat_jur - object
g06a - object
g06b - object
g12a - object
g12b - object
ge008 - object
ge009 - object
ge010 - object
ge011 - object
pop_tot - int64
pop_urb - int64
ge201 - object
ge202 - object
ag001 - object
ag002 - object
ag003 - object
ag004 - object
ag005 - object
ag006 - object
ag007 - object
ag008 - object
ag010 - object
ag011 - object
ag012 - object
ag013 - object
ag014 - object
ag015 - object
ag017 - object
ag018 - object
ag019 - object
ag020 - object
ag021 - object
ag022 - object
ag024 - object
ag026 - object
ag027 - object
ag028 - object
es001 - object
es002 - object
es003 - object
es004 - object
es005 - object
es006 - object
es007 - object
es008 - object
es009 - object
es012 - object
es013 - object
es014 - object
es015 - object
es026 - object
es028 - object
fn001 - object
fn002 - object
fn003 - object
fn004 - object
fn005 - object
fn006 - object
fn007 - object
fn008 - object
fn010 - object
fn011 - object
fn013 - object
fn014 - object
fn015 - object
fn016 - object
fn017 - object
fn018 - object
fn019 - object
fn020 - object
fn021 - object
fn022 - object
fn023 - object
fn024 - object
fn025 - object
fn026 - object
fn027 - object
fn028 - object
fn030 - object
fn031 - object
fn032 - object
fn033 - object
fn034 - object
fn035 - object
fn036 - object
fn037 - object
fn038 - object
fn039 - object
fn041 - object
fn042 - object
fn043 - object
fn044 - object
fn045 - object
fn046 - object
fn047 - object
fn048 - object
fn051 - object
fn052 - object
fn053 - object
fn054 - object
fn055 - object
fn056 - object
fn057 - object
fn058 - object
qd001 - object
qd002 - object
qd003 - object
qd004 - object
qd006 - object
qd007 - object
qd008 - object
qd009 - object
qd011 - object
qd012 - object
qd015 - object
qd016 - object
qd017 - object
qd019 - object
qd020 - object
qd021 - object
qd022 - object
qd023 - object
qd024 - object
qd025 - object
qd026 - object
qd027 - object
qd028 - object
qd029 - object
ca001 - object
ca002 - object
ca003 - object
ca004 - object
ca005 - object
ca006 - object
ca007 - object
ca008 - object
ca009 - object
cc010 - object
cc011 - object
cc012 - object
cc013 - object
cc014 - object
cc015 - object
cc016 - object
cc017 - object
cc018 - object
cc019 - object
cc020 - object
co001 - object
co002 - object
co003 - object
co004 - object
co008 - object
co012 - object
co013 - object
co014 - object
co019 - object
co020 - object
co021 - object
co022 - object
co050 - object
co051 - object
co052 - object
co053 - object
co054 - object
co055 - object
co056 - object
co057 - object
co058 - object
co059 - object
co060 - object
co061 - object
co062 - object
co063 - object
co064 - object
co065 - object
co066 - object
co067 - object
co068 - object
co069 - object
co070 - object
co071 - object
co072 - object
co073 - object
co074 - object
co075 - object
co076 - object
co077 - object
co078 - object
co079 - object
co080 - object
co081 - object
co082 - object
co083 - object
co084 - object
co085 - object
co086 - object
co087 - object
co088 - object
co089 - object
co090 - object
co091 - object
co092 - object
co093 - object
co094 - object
co095 - object
co096 - object
co097 - object
co098 - object
co099 - object
co100 - object
co101 - object
co102 - object
co103 - object
co104 - object
co105 - object
co106 - object
co107 - object
co108 - object
co109 - object
co110 - object
co111 - object
co112 - object
co113 - object
co114 - object
co115 - object
co116 - object
co117 - object
co118 - object
co119 - object
co120 - object
co121 - object
co122 - object
co123 - object
co124 - object
co125 - object
co126 - object
co127 - object
co128 - object
co129 - object
co130 - object
co131 - object
co133 - object
co134 - object
co135 - object
co136 - object
co137 - object
co138 - object
co139 - object
co140 - object
co141 - object
co142 - object
co143 - object
co144 - object
co145 - object
co146 - object
co147 - object
co148 - object
co149 - object
co150 - object
co151 - object
co152 - object
co154 - object
co155 - object
co156 - object
co157 - object
co158 - object
co159 - object
co160 - object
co161 - object
co162 - object
co163 - object
co164 - object
co165 - object
co170 - object
co171 - object
co172 - object
co173 - object
co174 - object
co175 - object
cp001 - object
cp002 - object
cp003 - object
cp004 - object
cs001 - object
cs002 - object
cs009 - object
cs010 - object
cs011 - object
cs012 - object
cs013 - object
cs014 - object
cs022 - object
cs023 - object
cs024 - object
cs025 - object
cs026 - object
cs027 - object
cs028 - object
cs029 - object
cs030 - object
cs031 - object
cs032 - object
cs033 - object
cs034 - object
cs035 - object
cs036 - object
cs037 - object
cs038 - object
cs039 - object
cs040 - object
cs041 - object
cs042 - object
cs043 - object
cs044 - object
cs045 - object
cs046 - object
cs047 - object
cs048 - object
cs049 - object
cs050 - object
cs053 - object
cs054 - object
cs055 - object
cs056 - object
cs057 - object
cs058 - object
cs059 - object
cs060 - object
fn201 - object
fn202 - object
fn203 - object
fn204 - object
fn205 - object
fn206 - object
fn207 - object
fn208 - object
fn209 - object
fn210 - object
fn211 - object
fn212 - object
fn213 - object
fn214 - object
fn215 - object
fn216 - object
fn217 - object
fn218 - object
fn219 - object
fn220 - object
fn221 - object
fn222 - object
fn223 - object
fn224 - object
fn225 - object
fn226 - object
fn227 - object
os001 - object
os003 - object
os004 - object
os005 - object
os006 - object
os007 - object
os008 - object
os009 - object
os010 - object
os011 - object
os012 - object
os014 - object
os015 - object
os016 - object
os017 - object
os018 - object
os019 - object
os020 - object
os021 - object
os022 - object
os023 - object
os025 - object
os026 - object
os027 - object
os028 - object
os029 - object
os030 - object
os031 - object
os032 - object
os033 - object
os040 - object
os041 - object
os042 - object
os043 - object
os044 - object
os045 - object
os046 - object
os047 - object
os048 - object
os049 - object
os050 - object
os051 - object
os052 - object
os053 - object
po001 - object
po002 - object
po004 - object
po005 - object
po006 - object
po007 - object
po008 - object
po009 - object
po010 - object
po011 - object
po012 - object
po013 - object
po014 - object
po015 - object
po016 - object
po017 - object
po018 - object
po019 - object
po020 - object
po021 - object
po022 - object
po023 - object
po024 - object
po025 - object
po026 - object
po027 - object
po028 - object
po029 - object
po031 - object
po033 - object
po034 - object
po035 - object
po036 - object
po037 - object
po038 - object
po039 - object
po040 - object
po041 - object
po042 - object
po043 - object
po044 - object
po045 - object
po046 - object
po047 - object
po048 - object
po049 - object
po050 - object
po051 - object
rs003 - object
rs004 - object
rs008 - object
rs009 - object
rs020 - object
rs021 - object
rs022 - object
rs023 - object
rs024 - object
rs025 - object
rs026 - object
rs027 - object
rs028 - object
rs030 - object
rs031 - object
rs034 - object
rs036 - object
rs038 - object
rs039 - object
rs040 - object
rs041 - object
rs042 - object
rs043 - object
rs044 - object
rs045 - object
rs046 - object
tb001 - object
tb002 - object
tb003 - object
tb004 - object
tb005 - object
tb006 - object
tb007 - object
tb008 - object
tb009 - object
tb010 - object
tb011 - object
tb012 - object
tb013 - object
tb014 - object
tb015 - object
tb016 - object
tb017 - object
tb018 - object
tb019 - object
tb020 - object
tb021 - object
tb022 - object
tb023 - object
tb024 - object
tb025 - object
tb026 - object
tb027 - object
tb028 - object
tb029 - object
tb030 - object
tb031 - object
tb032 - object
tb033 - object
tb034 - object
tb035 - object
va001 - object
va002 - object
va003 - object
va004 - object
va010 - object
va011 - object
va012 - object
va016 - object
va020 - object
va021 - object
va030 - object
va031 - object
va032 - object
va033 - object
va034 - object
va035 - object
va036 - object
va038 - object
va039 - object
in001_ae - object
in002_ae - object
in003_ae - object
in004_ae - object
in005_ae - object
in006_ae - object
in007_ae - object
in008_ae - object
in009_ae - object
in010_ae - object
in011_ae - object
in012_ae - object
in013_ae - object
in014_ae - object
in015_ae - object
in016_ae - object
in017_ae - object
in018_ae - object
in019_ae - object
in020_ae - object
in021_ae - object
in022_ae - object
in023_ae - object
in024_ae - object
in025_ae - object
in026_ae - object
in027_ae - object
in028_ae - object
in029_ae - object
in030_ae - object
in031_ae - object
in032_ae - object
in033_ae - object
in034_ae - object
in035_ae - object
in036_ae - object
in037_ae - object
in038_ae - object
in039_ae - object
in040_ae - object
in041_ae - object
in042_ae - object
in043_ae - object
in044_ae - object
in045_ae - object
in046_ae - object
in047_ae - object
in048_ae - object
in049_ae - object
in050_ae - object
in051_ae - object
in052_ae - object
in053_ae - object
in054_ae - object
in055_ae - object
in056_ae - object
in057_ae - object
in058_ae - object
in059_ae - object
in060_ae - object
in071_ae - object
in072_ae - object
in073_ae - object
in074_ae - object
in075_ae - object
in076_ae - object
in077_ae - object
in079_ae - object
in080_ae - object
in082_ae - object
in083_ae - object
in084_ae - object
in085_ae - object
in101_ae - object
in102_ae - object
in001_rs - object
in002_rs - object
in003_rs - object
in004_rs - object
in005_rs - object
in006_rs - object
in007_rs - object
in008_rs - object
in010_rs - object
in011_rs - object
in014_rs - object
in015_rs - object
in016_rs - object
in017_rs - object
in018_rs - object
in019_rs - object
in021_rs - object
in022_rs - object
in023_rs - object
in024_rs - object
in025_rs - object
in026_rs - object
in027_rs - object
in028_rs - object
in029_rs - object
in030_rs - object
in031_rs - object
in032_rs - object
in033_rs - object
in034_rs - object
in035_rs - object
in036_rs - object
in037_rs - object
in038_rs - object
in039_rs - object
in040_rs - object
in041_rs - object
in042_rs - object
in043_rs - object
in044_rs - object
in045_rs - object
in046_rs - object
in047_rs - object
in048_rs - object
in051_rs - object
in052_rs - object
in053_rs - object
in054_rs - object

##  Filtrar o dataframe "df_snis" para formar um novo dataframe "df_snis_2021"

In [9]:
# Selecionar apenas as colunas de abastecimento que decidi trabalhar
df_filtrado = df_snis[['cd_mun7', 'cd_mun6', 'nm_mun', 'uf', 'ano_ref', 'prestadores', 'servicos', 'nat_jur',
                'ge009','ge011','es002','es004','es005','es006','es007','es008','es009','in015_ae','in016_ae','in021_ae','in046_ae',
                'ge008', 'ge010','ag003','ag004','ag005','ag021','ag022','ag008','ag010','ag011','ag012','in003_ae','in005_ae','in028_ae','in049_ae']]

# filtrando para 2021
df_snis_2021 = df_filtrado[df_filtrado['ano_ref'] == '2021']

# Alterando o index dos novos dataframes filtrados porque eles herdaram o index do dataframe "df_snis_abastecimento" e "df_snis_esgotamento"
df_snis_2021 = df_snis_2021.reset_index(drop=True)

#Exibir o dataframe
df_snis_2021

,cd_mun7,cd_mun6,nm_mun,uf,ano_ref,prestadores,servicos,nat_jur,ge009,ge011,...,ag021,ag022,ag008,ag010,ag011,ag012,in003_ae,in005_ae,in028_ae,in049_ae
0,3300100,330010,Angra dos Reis,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Água | Res. Sólidos,Autarquia | Sociedade de economia mista com ad...,1.0,35.0,...,54616.0,25473.0,4472.22,15075.45,16985.16,0.0,2.76,2.83,78.64,30.2
1,3300159,330015,Aperibé,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Esgotos | Água | Água e Esgoto | Res. Sólidos,Administração pública direta | Sociedade de ec...,1.0,3.0,...,3578.0,3799.0,616.22,720.76,793.99,0.0,4.22,5.0,44.05,60.01
2,3300209,330020,Araruama,RJ,2021,[33002011] Concessionária Águas de Juturnaíba ...,Água e Esgoto | Res. Sólidos,Empresa privada | Administração pública direta,1.0,1.0,...,71225.0,66879.0,9641.86,15312.87,10581.55,21602.74,11.82,19.73,52.48,24.05
3,3300225,330022,Areal,RJ,2021,,,,,,...,,,,,,,,,,
4,3300233,330023,Armação dos Búzios,RJ,2021,[33007011] Prolagos S/A - Concessionária de Se...,Água e Esgoto | Res. Sólidos,Empresa privada | Administração pública direta,1.0,0.0,...,18628.0,23775.0,3417.0,3417.0,4242.0,6786.0,2.91,16.49,92.24,25.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
87,3306008,330600,Três Rios,RJ,2021,[33060011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,Autarquia | Administração pública direta,1.0,1.0,...,42821.0,27076.0,4698.0,9013.0,5306.0,10399.34,3.5,3.8,51.02,13.33
88,3306107,330610,Valença,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Esgotos | Água | Res. Sólidos,Administração pública direta | Sociedade de ec...,1.0,5.0,...,19105.0,19694.0,4302.72,5449.77,4350.79,0.0,5.82,4.45,37.72,52.75
89,3306156,330615,Varre-Sai,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água | Res. Sólidos,Sociedade de economia mista com administração ...,,,...,1094.0,1060.0,164.64,200.15,254.8,0.0,11.62,5.08,61.69,51.54
90,3306206,330620,Vassouras,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Esgotos | Água | Res. Sólidos,Administração pública direta | Sociedade de ec...,1.0,1.0,...,11008.0,12285.0,1673.75,2042.68,2754.17,0.0,5.44,5.25,69.6,48.38
91,3306305,330630,Volta Redonda,RJ,2021,[33063011] Serviço Autônomo de Água e Esgoto d...,Água e Esgoto | Res. Sólidos,Autarquia | Administração pública direta,1.0,0.0,...,90548.0,117746.0,16935.17,18517.81,20977.73,36753.56,2.84,3.0,57.08,49.62

# Processamento

## Estatística Descritiva

In [10]:
# Calcular a estatística descritiva básica do dataset para cada coluna numérica
df_snis_2021.describe()

,cd_mun7,cd_mun6,nm_mun,uf,ano_ref,prestadores,servicos,nat_jur,ge009,ge011,...,ag021,ag022,ag008,ag010,ag011,ag012,in003_ae,in005_ae,in028_ae,in049_ae
count,92,92,92,92,92,92,92,92,92.0,92.0,...,92,92,92.0,92,92,92.0,92,92,92,92
unique,92,92,92,1,1,92,19,27,3.0,14.0,...,91,84,87.0,91,90,32.0,88,76,90,91
top,3300100,330010,Angra dos Reis,RJ,2021,[33045500] Companhia Estadual de Águas e Esgot...,Água e Esgoto | Res. Sólidos,Sociedade de economia mista com administração ...,1.0,0.0,...,,,0.0,,,0.0,,,,
freq,1,1,1,92,92,1,26,16,75.0,25.0,...,2,7,5.0,2,2,60.0,4,6,2,2

In [13]:
def calcula_media_metrica_ano(metrica: str, ano: int, df: pd.DataFrame) -> float:
    """
    Função para retornar a média de uma métrica em um determinado ano
    metrica: nome da métrica
    ano: ano da métrica
    df: DataFrame a ser analisado
    """
    return df[df['ano_ref'] == str(ano)][metrica.lower()].mean(skipna=True)

def calcula_total_metrica_ano(metrica: str, ano: int, df: pd.DataFrame) -> float:
    """
    Função para retornar o total de uma métrica em um determinado ano
    metrica: nome da métrica
    ano: ano da métrica
    df: DataFrame a ser analisado
    """
    return df[df['ano_ref'] == str(ano)][metrica.lower()].sum(skipna=True)

In [14]:
# dicionário com os nomes e os indicadores
dicionario_indicadores_total = dict()

# Cálculo de fato dos indicadores
# GE008 - Quantidade de sedes municipais atendidas com abastecimento de água
ge008 = calcula_total_metrica_ano('GE008',2021,df_snis)
dicionario_indicadores_total['ge008'] = ge008

# GE009 - Quantidade de sedes municipais atendidas com esgotamento sanitário
ge009 = calcula_total_metrica_ano('GE009',2021,df_snis)
dicionario_indicadores_total['ge009'] = ge009

# GE010 - Quantidade de localidades (excluídas as sedes) atendidas com abastecimento de água
ge010 = calcula_total_metrica_ano('GE010',2021,df_snis)
dicionario_indicadores_total['ge010'] = ge010

# GE011 - Quantidade de localidades (excluídas as sedes) atendidas com esgotamento sanitário
ge011 = calcula_total_metrica_ano('GE011',2021,df_snis)
dicionario_indicadores_total['ge010'] = ge010

# AG003 - Quantidade de economias ativas de água 
ag003 = calcula_total_metrica_ano('AG003',2021,df_snis)
dicionario_indicadores_total['ag003'] = ag003

# AG004 - Quantidade de ligações ativas de Água Micromedidas 
ag004 = calcula_total_metrica_ano('AG004',2021,df_snis)
dicionario_indicadores_total['ag004'] = ag004

# AG005 - Extensão da Rede de Água (km)
ag005 = calcula_total_metrica_ano('AG005',2021,df_snis)
dicionario_indicadores_total['ag005'] = ag005

# AG008 - Volume de água micromedido
ag008 = calcula_total_metrica_ano('AG008',2021,df_snis)
dicionario_indicadores_total['ag008'] = ag008

# AG010 - Volume de água consumido
ag010 = calcula_total_metrica_ano('AG010',2021,df_snis)
dicionario_indicadores_total['ag010'] = ag010

# AG011 - Volume de água faturado
ag011 = calcula_total_metrica_ano('AG011',2021,df_snis)
dicionario_indicadores_total['ag011'] = ag011

# AG012 - Volume de água Macromedido
ag012 = calcula_total_metrica_ano('AG012',2021,df_snis)
dicionario_indicadores_total['ag012'] = ag012

# AG021 - Quantidade de Ligações Totais de Água
ag021 = calcula_total_metrica_ano('AG021',2021,df_snis)
dicionario_indicadores_total['ag021'] = ag021

# AG022 - Quantidade de economias residenciais ativas de água Micromedidas
ag022 = calcula_total_metrica_ano('AG022',2021,df_snis)
dicionario_indicadores_total['ag022'] = ag022

# ES002 - Quantidade de ligações ativas de esgoto
es002 = calcula_total_metrica_ano('ES002',2021,df_snis)
dicionario_indicadores_total['es002'] = es002

# ES004 - Extensão da rede de esgotos
es004 = calcula_total_metrica_ano('ES004',2021,df_snis)
dicionario_indicadores_total['es004'] = es004

# ES005 - Volume de esgotos coletado
es005 = calcula_total_metrica_ano('ES005',2021,df_snis)
dicionario_indicadores_total['es005'] = es005

# ES006 - Volume de esgoto tratado
es006 = calcula_total_metrica_ano('ES006',2021,df_snis)
dicionario_indicadores_total['es006'] = es006

# AG007 - Volume de esgotos faturado
es007 = calcula_total_metrica_ano('ES007',2021,df_snis)
dicionario_indicadores_total['es007'] = es007

# ES008 - Quantidade de economias residenciais ativas de esgoto
es008 = calcula_total_metrica_ano('ES008',2021,df_snis)
dicionario_indicadores_total['es008'] = es008

# ES009 - Quantidade de ligações totais de esgoto
es009 = calcula_total_metrica_ano('ES009',2021,df_snis)
dicionario_indicadores_total['es009'] = es009

'''-------------------------------------------------------------------------------------------------------------'''

# * médias
# São calculadas usando do dataframe completo "df" e não o dataframe filtrado

# dicionário com os nomes e os indicadores
dicionario_indicadores_medias = dict()

# Cálculo de fato dos indicadores
# 'IN003_AE': Despesa total com os serviços por M³ faturado - (R$/M³)
# 'IN003_AE' = (FN017 / AG011 + ES007) * 1/1000
fn017 = calcula_media_metrica_ano('FN017', 2021, df_snis)
ag011 = calcula_media_metrica_ano('AG011', 2021, df_snis)
es007 = calcula_media_metrica_ano('ES007', 2021, df_snis)
in003_ae = (fn017 / ag011 + es007) * 1/1000
dicionario_indicadores_medias['in003_ae'] = in003_ae

# 'IN005_AE': Tarifa média de água - (R$/M³)
# 'IN005_AE' = (FN002 / AG011 - AG017 - AG019) * 1/1000
fn002 = calcula_media_metrica_ano('fn002', 2021, df_snis)
ag011 = calcula_media_metrica_ano('AG011', 2021, df_snis)
ag017 = calcula_media_metrica_ano('AG017', 2021, df_snis)
ag019 = calcula_media_metrica_ano('AG019', 2021, df_snis)
in005_ae = (fn002 / ag011 - ag017 - ag019) * 1/1000
dicionario_indicadores_medias['in005_ae'] = in005_ae

# 'IN049_AE': Índice de Perdas na Distribuição
# 'IN049_AE' = (AG006 + AG018 - AG010 - AG024 / AG006 + AG018 - AG024) * 100
ag006 = calcula_media_metrica_ano('ag006', 2021, df_snis)
ag010 = calcula_media_metrica_ano('ag010', 2021, df_snis)
ag018 = calcula_media_metrica_ano('ag018', 2021, df_snis)
ag024 = calcula_media_metrica_ano('ag024', 2021, df_snis)
in049_ae = (ag006 + ag018 - ag010 - ag024 / ag006 + ag018 - ag024) * 100
dicionario_indicadores_medias['in049_ae'] = in049_ae


# 'IN015_AE': Índice de Perdas na Distribuição (%)
# 'IN015_AE' = (ES005 / AG010 - AG019) * 100
es005 = calcula_media_metrica_ano('ES005', 2021, df_snis)
ag010 = calcula_media_metrica_ano('AG010',2021, df_snis)
ag019 = calcula_media_metrica_ano('AG019', 2021, df_snis)
in015_ae = (es005 / ag010 - ag019) * 100
dicionario_indicadores_medias['in015_ae'] = in015_ae

# 'IN016_AE': Índice de Perdas na Distribuição (%)
# 'IN016_AE' = (ES006 + ES014 + ES015 / ES005 + ES013) * 100
es005 = calcula_media_metrica_ano('ES005', 2021, df_snis)
es006 = calcula_media_metrica_ano('ES006', 2021, df_snis)
es013 = calcula_media_metrica_ano('ES013', 2021, df_snis)
es014 = calcula_media_metrica_ano('ES014', 2021, df_snis)
es015 = calcula_media_metrica_ano('ES015', 2021, df_snis)
in016_ae = (es006 + es014 + es015 / es005 + es013) * 100
dicionario_indicadores_medias['in016_ae'] = in016_ae

# 'IN021_AE': Extensão da rede de esgoto por ligação (m/lig)
# 'IN021_AE' = 
es004 = calcula_media_metrica_ano('ES004', 2021, df_snis)
es009 = calcula_media_metrica_ano('ES009', 2021, df_snis)
in021_ae = (es004 / es009) * 1000
dicionario_indicadores_medias['in021_ae'] = in021_ae

# 'IN046_AE': Índice de esgoto tratado referido a água consumida
# 'IN046_AE' = 
es006 = calcula_media_metrica_ano('ES006', 2021, df_snis)
es015 = calcula_media_metrica_ano('ES015', 2021, df_snis)
ag010 = calcula_media_metrica_ano('AG010', 2021, df_snis)
ag019 = calcula_media_metrica_ano('AG019', 2021, df_snis)
in046_ae = (es006 + es015 / ag010 - ag019) * 100
dicionario_indicadores_medias['in046_ae'] = in046_ae

TypeError: unsupported operand type(s) for +: 'float' and 'str'

In [ ]:
linha_valor_erj = pd.DataFrame([
                                {'cd_mun7' : 333, 'cd_mun6': 333000, 'nm_mun': 'Valor para ERJ', 'uf':'RJ','ano_ref': '2021', 'prestadores': 'não se aplica', 'servicos': 'não se aplica', 'nat_jur':'nat_jur'}
                                |dicionario_indicadores_medias
                                |dicionario_indicadores_total
                                ])
linha_valor_erj.index = [92]

# inserindo linha com total e médias, nesta ordem
df_snis_2021 = pd.concat([df_snis_2021, linha_valor_erj])

df_snis_2021

# Conexão e Importação para Banco de Dados

## Usando a biblioteca sqlalchemy para importar os DataFrames após a etapa de Data Cleaning

In [ ]:
# CONEXÃO COM BANCO DE DADOS LOCAL

from sqlalchemy import create_engine

# Substitua os valores entre chaves {} pelos seus próprios dados
conexao  = 'postgresql://{}:{}@localhost:{}/{}'.format('postgres','MudarePreciso123','5432','gisdb') # SINTAXE: usuario:senha@localhost:porta/database

#Criar uma engine de conexão
engine = create_engine(conexao)

# Exibir a string de conexão
print(conexao )

df_snis.to_sql('df_snis', engine, schema='saneamento', if_exists='replace', index=True)
df_snis_2021.to_sql('df_snis_2021', engine, schema='saneamento', if_exists='replace', index=True)

# Fecha a conexão com o banco
engine.dispose()